# Generated by Django 5.1.7 on 2025-04-12 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_initial_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Questions'), ('treatment', 'Treatment Related'), ('appointment', 'Appointment Related'), ('insurance', 'Insurance & Payment')], max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'question'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='what_to_expect',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('service_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service')),
            ],
        ),
    ]
