# Generated by Django 5.1.7 on 2025-04-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_service_price_calculator_patientportal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualconsultation',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='virtualconsultation',
            name='service',
        ),
        migrations.AddField(
            model_name='virtualconsultation',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtualconsultation',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtualconsultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='virtualconsultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
